spring.application.name=clientes-api

spring.datasource.url=jdbc:h2:mem:clientesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.br.com.posxp.clientesapi=INFO
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=clientes-api
info.app.description=API REST MVC para gerenciamento de clientes
info.app.version=0.0.1-SNAPSHOT
info.app.java.version=17
